/*
 * Auto-generated by STM32 Block IDE.
 * DO NOT EDIT BY HAND - your changes will be overwritten on the next build.
 *
 * Board:    NUCLEO-F446RE
 * Step:     1 ms
 * Blocks:   3
 */

#include "stm32f4xx_hal.h"
#include <stdio.h>
#include <string.h>

/* ------------------------------------------------------------------- */
/* Block signals                                                       */
/* ------------------------------------------------------------------- */
static float sig_SquareWave_1_y = 0.0f;
static float phase_SquareWave_1 = 0.0f;

/* ------------------------------------------------------------------- */
/* Forward decls                                                       */
/* ------------------------------------------------------------------- */
static void SystemClock_Config(void);
static void Error_Handler(void);
static void MX_GPIO_Init(void);
static void MX_USART2_UART_Init(void);
static void model_step(void);
static void scope_emit(void);

UART_HandleTypeDef huart2;

volatile uint32_t step_tick_flag = 0;

void SysTick_Handler(void) {
    HAL_IncTick();
    /* Generated step rate: every 1 ms */
    static uint32_t cnt = 0;
    cnt++;
    if (cnt >= 1) {
        cnt = 0;
        step_tick_flag = 1;
    }
}

int main(void) {
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART2_UART_Init();

    while (1) {
        if (step_tick_flag) {
            step_tick_flag = 0;
            model_step();
            scope_emit();
        }
    }
}

/* ------------------------------------------------------------------- */
static void model_step(void) {
    /* block SquareWave_1: SquareWave */
    phase_SquareWave_1 += 2.000000f * 0.001000f;
    if (phase_SquareWave_1 >= 1.0f) phase_SquareWave_1 -= 1.0f;
    sig_SquareWave_1_y = (phase_SquareWave_1 < 0.500000f) ? 1.000000f : 0.000000f;
    /* block GpioOut_2: GpioOut PA5 */
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, (sig_SquareWave_1_y > 0.500000f) ? GPIO_PIN_SET : GPIO_PIN_RESET);
    /* block Scope_3: Scope (stream) */
}

/* ------------------------------------------------------------------- */
/* Stream scope channels over USART2 as comma-separated floats.        */
/* ------------------------------------------------------------------- */
static void scope_emit(void) {
    char buf[96];
    int n = snprintf(buf, sizeof(buf), "%.4f\r\n", sig_SquareWave_1_y);
    if (n > 0) HAL_UART_Transmit(&huart2, (uint8_t*)buf, n, 10);

}

/* ------------------------------------------------------------------- */
/* Board init                                                          */
/* ------------------------------------------------------------------- */
static void MX_GPIO_Init(void) {
    GPIO_InitTypeDef gi = {0};
    __HAL_RCC_GPIOA_CLK_ENABLE();
    gi.Pin = GPIO_PIN_5;
    gi.Mode = GPIO_MODE_OUTPUT_PP;
    gi.Pull = GPIO_NOPULL;
    gi.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOA, &gi);
}

static void MX_USART2_UART_Init(void) {
    __HAL_RCC_USART2_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();

    GPIO_InitTypeDef gi = {0};
    gi.Pin = GPIO_PIN_2 | GPIO_PIN_3;
    gi.Mode = GPIO_MODE_AF_PP;
    gi.Pull = GPIO_NOPULL;
    gi.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    gi.Alternate = GPIO_AF7_USART2;
    HAL_GPIO_Init(GPIOA, &gi);

    huart2.Instance = USART2;
    huart2.Init.BaudRate = 115200;
    huart2.Init.WordLength = UART_WORDLENGTH_8B;
    huart2.Init.StopBits = UART_STOPBITS_1;
    huart2.Init.Parity = UART_PARITY_NONE;
    huart2.Init.Mode = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;
    if (HAL_UART_Init(&huart2) != HAL_OK) Error_Handler();
}

static void SystemClock_Config(void) {
    RCC_OscInitTypeDef osc = {0};
    RCC_ClkInitTypeDef clk = {0};

    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    osc.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    osc.HSIState = RCC_HSI_ON;
    osc.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    osc.PLL.PLLState = RCC_PLL_ON;
    osc.PLL.PLLSource = RCC_PLLSOURCE_HSI;
    osc.PLL.PLLM = 16; osc.PLL.PLLN = 360;
    osc.PLL.PLLP = RCC_PLLP_DIV2; osc.PLL.PLLQ = 7;
    if (HAL_RCC_OscConfig(&osc) != HAL_OK) Error_Handler();
    if (HAL_PWREx_EnableOverDrive() != HAL_OK) Error_Handler();

    clk.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                  | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    clk.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    clk.AHBCLKDivider = RCC_SYSCLK_DIV1;
    clk.APB1CLKDivider = RCC_HCLK_DIV4;
    clk.APB2CLKDivider = RCC_HCLK_DIV2;
    if (HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_5) != HAL_OK) Error_Handler();
}

static void Error_Handler(void) {
    while (1) { /* spin */ }
}
